version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      action-runtime:
        patterns:
          - '@actions/*'
      build-tooling:
        patterns:
          - '@vercel/ncc'
          - 'typescript'
        update-types:
          - minor
          - patch
      node-types:
        patterns:
          - '@types/node'
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - '*'
